# Generated by Django 4.2.7 on 2023-11-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
